[package]
name = "hsrm-bachelor-thesis"
entrypoint = "lib.typ"
description = "Unofficial template for writing a bachelor-thesis in the Hochschule Rhein Main department of Computer Science design. Fork from the HAW-Hamburg template."
categories = ["thesis"]

[template]
path = "src"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
