[package]
version = "0.6.0"
compiler = "0.13.0"
authors = ["Simon Johannes Engelhardt", "Lasse Rosenow"]
license = "MIT"
repository = "https://github.com/SimonJohannesEngelhardt/HSRM-Typist-Template"
